Adjustments for AWS deployment

diff --git a/deploy/enable_cronjobs b/deploy/enable_cronjobs
--- a/deploy/enable_cronjobs
+++ b/deploy/enable_cronjobs
@@ -1,15 +1,36 @@
 #!/bin/bash
 #
-# 
+# *** Pets-Deli deployment
+#
+# enable_cronjobs
+# This script is executed on tools host (as $www_user user) in order to activate cronjobs
+#
 #
 
-FILEPATH=`pwd`/$0; BASEDIR=`dirname $FILEPATH`; . $BASEDIR/vars; source $BASEDIR/functions
-outfile="/tmp/deploy-${deploy_outfile_prefix}-enable-cronjobs"
-`touch $outfile`
+#Exit if a command exits with a non-zero status
+set -e
 
-export APPLICATION_ENV=$environment
+#Exit if an uninitialised variable is used
+set -o nounset
 
-vendor/bin/pav-console setup:jenkins:generate
+FILEPATH=`pwd`/$0
+BASEDIR=`dirname $FILEPATH`
+source "$BASEDIR/vars"
+source "$BASEDIR/functions"
+outfile=`mktemp /tmp/deploy-XXXXXX`
 
-rm -rf $outfile
+# Prepare Jenkins - get roles for current hosts and call console if there are any roles for current host.
+cd "$destination_release_dir"
+roles=`get_cronjob_roles | sed 's/\([^ ]*\)/--role \1/g'`
+if [ -z "$roles" ]; then
+  echo "No cronjobs on this host"
+  roles="empty"
+else
+  echo "Installing cronjobs for roles: $roles"
+fi
+
+APPLICATION_ENV="${environment}" vendor/bin/pav-console setup:jenkins:generate $roles
+APPLICATION_ENV="${environment}" vendor/bin/pav-console setup:jenkins:enable
+
+rm -f "$outfile"
 exit 0
