salt fixes

diff --git a/deploy/prepare_code b/deploy/prepare_code
--- a/deploy/prepare_code
+++ b/deploy/prepare_code
@@ -35,7 +35,7 @@ if is_default_store; then
   # Prepare and get cache contents
   composer_cache_dir=/data/deploy/${environment}/vendor
   [ ! -d $composer_cache_dir ] && mkdir -p $composer_cache_dir
-  cp -r $composer_cache_dir ./
+  cp -r --reflink=auto $composer_cache_dir ./
 
   php -d "newrelic.appname='Deploy($environment)'" composer.phar self-update &> /dev/null
   if [ "${environment}" == "production" ]; then
@@ -47,6 +47,16 @@ if is_default_store; then
   # rsync current vendor back to the cache
   rsync -ra --delete vendor/ $composer_cache_dir/
 
+  # remove .git dirs from vendor folder to make it smaller
+  find vendor/ -type d -name .git | xargs rm -rf
+
+  # hotfix - remove .war files from infrastructure package to make tarball lighter
+  # - it should be removed from git directly
+
+  if [ ${environment} != "testing" ]; then
+    rm -f vendor/project-a/infrastructure-package/bin/*.war
+  fi
+
   # Log used packages version in renepro repository
   curl -s -XPUT -d @composer.lock http://renepro.project-a.com/deploy.php?hostname=`hostname`\\\&environment=$environment | grep -v 'logged'
 fi
@@ -55,7 +65,7 @@ fi
 if is_default_store; then
   generated_cache_dir=/data/deploy/${environment}/Generated
   [ ! -d $generated_cache_dir ] && mkdir -p $generated_cache_dir
-  cp -r $generated_cache_dir src/
+  cp -r --reflink=auto $generated_cache_dir src/
   rm -rf src/Generated/Zed/PropelGen
 fi
 
@@ -90,6 +100,18 @@ if is_default_store; then
   fi
 fi
 
+### Generate Code for NoSQL
+if is_default_store; then
+  echo " - generate nosql loader code"
+  APPLICATION_ENV=$environment sudo -E -u www-data php -d "newrelic.appname='Deploy($environment)'" vendor/bin/console nosql:generate &> $outfile
+  if [ $? -ne 0 ]; then
+    echo "!!! FATAL: There was an error in console nosql:generate"
+    cat $outfile
+    exit 2
+  fi
+fi
+
+
 ### Save the "Generated" dir back in cache
 rsync -ra --delete src/Generated/ $generated_cache_dir
 
@@ -104,7 +126,7 @@ if is_default_store; then
   # Prepare and get cache contents
   npm_cache_dir=/data/deploy/${environment}/node_modules
   [ ! -d $npm_cache_dir ] && mkdir -p $npm_cache_dir
-  cp -r $npm_cache_dir ./
+  cp -r --reflink=auto $npm_cache_dir ./
 
   # Install node dependencies
   export PATH=${PATH}:/var/lib/gems/1.8/bin
@@ -117,14 +139,14 @@ if is_default_store; then
   # Run grunt deployment tasks
   for app in Yves Zed; do
     echo " - grunt dist: $app"
-    grunt dist -gruntfile config/$app/Gruntfile.js >> $outfile
+    APPLICATION_STORE=${APPLICATION_STORE} APPLICATION_ENV=${environment} grunt dist -gruntfile config/$app/Gruntfile.js >> $outfile
     if [ $? -ne 0 ]; then
       echo "!!! FATAL: grunt failed"
       cat $outfile
       echo " --- to force deployment with failing grunt, edit deploy/prepare_code file ---"
       ###
       ### Remove (or comment out) next line to ignore grunt errors during deployment.
-      ### this shouls be used as hotfix only
+      ### this should be used as hotfix only
       ###
       exit 2
     fi
