- generate propel entities before distributing the source code in deployment - add gulp build for zed and remove grunt build for zed

diff --git a/deploy/prepare_code b/deploy/prepare_code
--- a/deploy/prepare_code
+++ b/deploy/prepare_code
@@ -71,19 +71,10 @@ fi
 
 chown -R www-data. .
 
-## ZED - Execute install.php
-echo " - propel setup"
-APPLICATION_ENV=$environment sudo -E -u www-data php -d "newrelic.appname='Deploy($environment)'" vendor/bin/console setup:propel:install -s ${APPLICATION_STORE} -e ${environment} &> $outfile
-if [ $? -ne 0 ]; then
-  echo "!!! FATAL: There was an error in console setup:propel:install"
-  cat $outfile
-  exit 1
-fi
-
 ### Generate Code
 if is_default_store; then
   echo " - generate code"
-  APPLICATION_ENV=$environment sudo -E -u www-data php -d "newrelic.appname='Deploy($environment)'" vendor/bin/console setup:generate &> $outfile
+  APPLICATION_ENV=$environment sudo -E -u www-data php -d "newrelic.appname='Deploy($environment)'" vendor/bin/console setup:propel:build:model &> $outfile
   if [ $? -ne 0 ]; then
     echo "!!! FATAL: There was an error in console setup:generate"
     cat $outfile
@@ -116,20 +107,26 @@ if is_default_store; then
   rsync -ra --delete node_modules/ $npm_cache_dir
 
   # Run grunt deployment tasks
-  for app in Yves Zed; do
-    echo " - grunt dist: $app"
-    APPLICATION_STORE=${APPLICATION_STORE} APPLICATION_ENV=${environment} grunt dist -gruntfile config/$app/Gruntfile.js >> $outfile
-    if [ $? -ne 0 ]; then
-      echo "!!! FATAL: grunt failed"
-      cat $outfile
-      echo " --- to force deployment with failing grunt, edit deploy/prepare_code file ---"
-      ###
-      ### Remove (or comment out) next line to ignore grunt errors during deployment.
-      ### this should be used as hotfix only
-      ###
-      exit 2
-    fi
-  done
+  echo " - grunt dist: Yves"
+  APPLICATION_STORE=${APPLICATION_STORE} APPLICATION_ENV=${environment} grunt dist -gruntfile config/Yves/Gruntfile.js >> $outfile
+  if [ $? -ne 0 ]; then
+    echo "!!! FATAL: grunt failed"
+    cat $outfile
+    echo " --- to force deployment with failing grunt, edit deploy/prepare_code file ---"
+    ###
+    ### Remove (or comment out) next line to ignore grunt errors during deployment.
+    ### this should be used as hotfix only
+    ###
+    exit 2
+  fi
+
+  "echo - gulp dist: Zed"
+  [ -z `which gulp` ] && npm install -g gulp
+  pushd ./vendor/spryker/zed-package
+  npm install --silent
+  gulp
+  popd
+  APPLICATION_STORE=${APPLICATION_STORE} APPLICATION_ENV=${environment} gulp dist -gulpfile config/$app/Gulpfile.js >> $outfile
 fi
 
 ### Allright, no error, deployment continues.
