- add more needed propel steps to generate propel related code in deployment

diff --git a/deploy/prepare_code b/deploy/prepare_code
--- a/deploy/prepare_code
+++ b/deploy/prepare_code
@@ -73,7 +73,23 @@ chown -R www-data. .
 
 ### Generate Code
 if is_default_store; then
-  echo " - generate code"
+  echo " - generating propel config code"
+  APPLICATION_ENV=$environment sudo -E -u www-data php -d "newrelic.appname='Deploy($environment)'" vendor/bin/console setup:propel:config:convert &> $outfile
+  if [ $? -ne 0 ]; then
+    echo "!!! FATAL: There was an error in console setup:generate"
+    cat $outfile
+    exit 2
+  fi
+
+  echo " - copy propel schemata"
+  APPLICATION_ENV=$environment sudo -E -u www-data php -d "newrelic.appname='Deploy($environment)'" vendor/bin/console setup:propel:schema:copy &> $outfile
+  if [ $? -ne 0 ]; then
+    echo "!!! FATAL: There was an error in console setup:generate"
+    cat $outfile
+    exit 2
+  fi
+
+  echo " - building propel entities and queries"
   APPLICATION_ENV=$environment sudo -E -u www-data php -d "newrelic.appname='Deploy($environment)'" vendor/bin/console setup:propel:build:model &> $outfile
   if [ $? -ne 0 ]; then
     echo "!!! FATAL: There was an error in console setup:generate"
